### ISSUE TITLE
cisco nexus 93180 fx3 not working

### ISSUE THREAD

**Issue by bienkma** [dsx1123/telemetry_collector#11]
Hi,
I got an issue when integrate nx 93180fx3 nxos 10.2(5) with telegraft (your repository). 
My configuration below:
```
telemetry
  certificate /bootflash/cert.pem telegraf
  destination-group 1
    ip address x.x.x.1 port 57000 protocol gRPC encoding GPB 
    certificate /bootflash/cert.pem telegraf
  sensor-group 1
    data-source NATIVE
    path microburst
  subscription 1
    dst-grp 1
    snsr-grp 1 sample-interval 0
```
then
```
show telemetry transport 

Session Id  Dst Grp  IP Address      Port       Encoding     Transport  Status    
--------------------------------------------------------------------------------
0           1        x.x.x.1    57000      GPB          gRPC       Transmit Error
--------------------------------------------------------------------------------
```
I tried telnet from nexus switch to x.x.x.1 port 57000, port listen and telnet work fine. Any idea to resolve the issue?

**Comment by dsx1123** [comment]
Not sure whether the collector is reachable from default vrf, as it will use default vrf by default, if you would like to change the vrf, add below commands to telemetry configuration:
```
telemetry
  certificate /bootflash/telegraf.crt telegraf
  destination-profile
    use-vrf management
```

**Comment by bienkma** [comment]
Correct. I added use-vrf default and the status is corrected now. But I can't get any microburst metrics (check micrburst event on switch had).

**Comment by bienkma** [comment]
I created an issue on https://github.com/CiscoDevNet/nx-telemetry-proto/issues/2

**Comment by dsx1123** [comment]
telegraf plugin need be updated, will create a PR on telegraf soon

**Comment by dsx1123** [comment]
PR opened. https://github.com/influxdata/telegraf/pull/13877

**Comment by dsx1123** [comment]
the PR has been merged into the telegraf, closing this issue
