### ISSUE TITLE
telegraf container restart loop

### ISSUE THREAD

**Issue by galc95** [dsx1123/telemetry_collector#9]
Hi, 
First of all amazing job, this looks great.
We have an issue with a clean build.
After stopping and starting via build.sh, the telegraf container is stuck in a reload loop.
Is this a known issue? Could it be caused by faulty config? (only changes were switch IPs and uncomment for tls)

**Comment by dsx1123** [comment]
@galc95  sorry for replying you late, not sure why I didn't get any notification, you can use docker logs -f telegraf to check what's the issue, it could be invalid configuration, but check the latest code to see if it works for you.
